### ISSUE TITLE
How to reproduce experiments on the Lambdanet dataset?

### ISSUE THREAD

**Issue by ItshallBe** [joernio/joernti-codetidal5#3]
Hi, I am interested in CodeTIDAL5 and it gives me great inspiration. But I can't find the code to reproduce experiments on the Lambdanet dataset. Can someone help me ?:) It would be great help!

**Comment by DavidBakerEffendi** [comment]
Right, I see only MTS4S here, will assign Lukas

**Comment by ItshallBe** [comment]
> Right, I see only MT4TS here, will assign Lukas

Thanks!

**Comment by pr0me** [comment]
Hey, so I don't seem to have access to the repository we used during development anymore.
I remember that the LambdaNet stuff was _tedious_ stuff and I never wrote a clean script for it.  

The authors published their experiment results as a weird collection of html pages.
You can find them here: https://github.com/MrVPlusOne/LambdaNet/blob/master/LambdaNet-Experiments.zip
You basically have to parse all files in `LambdaNet-Experiments/lambdaNet-epoch72/predictions` to get the correct type prediction for every object/variable.  
Red is wrong, green is correct, pink (`UNKNOWN` or `any`) do not count.
Then, we did some data cleaning for our dataflow use case:
```
In accordance with our goal to use type inference for dataflow analysis, we remove  
uninteresting objects from the dataset. First, we remove the non-expressive type  
annotations Function and void from the sample set. Secondly, we only consider variables with  
usages besides assignments. We also remove objects being  
part of class definitions, as we will infer types inside any function which uses or  
accesses such class members and, again, their occurrence purely as part of a definition is  
uninteresting from a dataflow point of view
```

To get the actual data, you can checkout the repositories at the corresponding commit from this list from LambdaNet: https://github.com/MrVPlusOne/LambdaNet/blob/master/data/repo-SHAs.txt 

Really sorry I cannot provide you with a clean and quick script to reran experiments right now :/
but I hope this helps a little.

**Comment by ItshallBe** [comment]
> Hey, so I don't seem to have access to the repository we used during development anymore. I remember that the LambdaNet data was _tedious_ stuff to work with and I never cleaned up our scripts enough to publish them...
> 
> The authors published their experiment results as a weird collection of html pages. You can find them here: https://github.com/MrVPlusOne/LambdaNet/blob/master/LambdaNet-Experiments.zip You basically have to parse all files in `LambdaNet-Experiments/lambdaNet-epoch72/predictions` to get the correct type prediction for every object/variable. Red is wrong, green is correct, pink (`UNKNOWN` or `any`) do not count. Then, we did some data cleaning for our dataflow use case:
> 
> ```
> In accordance with our goal to use type inference for dataflow analysis, we remove  
> uninteresting objects from the dataset. First, we remove the non-expressive type  
> annotations Function and void from the sample set. Secondly, we only consider variables with  
> usages besides assignments. We also remove objects being  
> part of class definitions, as we will infer types inside any function which uses or  
> accesses such class members and, again, their occurrence purely as part of a definition is  
> uninteresting from a dataflow point of view
> ```
> 
> To get the actual data, you can checkout the repositories at the corresponding commit from this list from LambdaNet: https://github.com/MrVPlusOne/LambdaNet/blob/master/data/repo-SHAs.txt
> 
> Really sorry I cannot provide you with a clean and quick script to reran experiments right now :/ but I hope this helps a little.

Thanks for your response! I appreciate the time you took to respond. I will look into LambdaNet and try to write a script for handling data in your experiment. If I run into more issues, I might reach out again for help.:)

**Comment by pr0me** [comment]
closing this for now.
if you have further questions, feel free to re-open or create a new issue.
